"""Decision Support Engine (DSE) — advisory-only (ADR-084, T7.1).

Explainable recommendations (utility + Kelly/Half-Kelly + mock sentiment/stress).
No auto-execution, no signing, no key custody, no gamification.
"""

from .engine import DseEngine, MockDseEngine
from .models import (
    Action,
    ActionCategory,
    ActionType,
    AnalyticsContext,
    DecisionTrace,
    DecisionTraceStep,
    EarnAlternative,
    EarnMetrics,
    Greeks,
    GreeksSummary,
    ModelVersions,
    PartnerContext,
    Position,
    ProductMetadata,
    Recommendation,
    RecommendRequest,
    RecommendResponse,
    RiskMetrics,
    RiskProfile,
    SentimentScore,
    StressScenario,
    StressTests,
    UtilityComponent,
    UtilityWeights,
)
from .profiles import AGGRESSIVE, BALANCED, CONSERVATIVE, weights_for
from .provider_foundation import (
    DYDX_EXCHANGE_PROVIDER,
    DYDX_MARKET_PROVIDER,
    FoundationProviders,
    MarketDataProvider,
    MarketSnapshot,
    ProviderTier,
    foundation_profile,
    resolve_exchange_route,
    resolve_foundation,
    resolve_market_data_route,
)
from .provider_layer import (
    LiveProviderNotWiredError,
    ProviderMode,
    ProviderProfile,
    assert_mock_only,
    provider_profile,
)
from .providers import (
    MockSentimentProvider,
    MockStressProvider,
    SentimentProvider,
    StressProvider,
    build_sentiment_provider,
    build_stress_provider,
)

__all__ = [
    "DseEngine",
    "MockDseEngine",
    "ActionType",
    "ActionCategory",
    "RiskProfile",
    "UtilityWeights",
    "Action",
    "Position",
    "SentimentScore",
    "StressScenario",
    "StressTests",
    "Recommendation",
    "ModelVersions",
    "Greeks",
    "GreeksSummary",
    "RiskMetrics",
    "EarnMetrics",
    "EarnAlternative",
    "AnalyticsContext",
    "DecisionTrace",
    "DecisionTraceStep",
    "PartnerContext",
    "ProductMetadata",
    "UtilityComponent",
    "RecommendRequest",
    "RecommendResponse",
    "CONSERVATIVE",
    "BALANCED",
    "AGGRESSIVE",
    "weights_for",
    "SentimentProvider",
    "StressProvider",
    "MockSentimentProvider",
    "MockStressProvider",
    "build_sentiment_provider",
    "build_stress_provider",
    "ProviderMode",
    "ProviderProfile",
    "LiveProviderNotWiredError",
    "provider_profile",
    "assert_mock_only",
    "ProviderTier",
    "MarketDataProvider",
    "MarketSnapshot",
    "FoundationProviders",
    "resolve_foundation",
    "foundation_profile",
    "DYDX_MARKET_PROVIDER",
    "DYDX_EXCHANGE_PROVIDER",
    "resolve_market_data_route",
    "resolve_exchange_route",
]
